version: '3.8'
services:
  parada-mysql:
    container_name: parada-mysql
    image: mysql:8.0.29
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=parada
    ports:
      - "127.0.0.1:3304:3306"
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
